// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using MyFlix.DAO.Models;

namespace MyFlix.DAO.Data;

public partial class MyFlixDbContext : IdentityDbContext
{

    public MyFlixDbContext()
    {
    }
    public MyFlixDbContext(DbContextOptions<MyFlixDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Filme> Filme { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        modelBuilder.Entity<Filme>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PK__Filme__3214EC07F7374424");

            entity.Property(e => e.AnoLancamento)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("ANO_LANCAMENTO");
            entity.Property(e => e.DataCadastro)
                .HasDefaultValueSql("(getdate())")
                .HasColumnType("datetime")
                .HasColumnName("DATA_CADASTRO");
            entity.Property(e => e.Genero)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("GENERO");
            entity.Property(e => e.Nota)
                .HasDefaultValue(1)
                .HasColumnName("NOTA");
            entity.Property(e => e.StatusAssistido).HasColumnName("STATUS_ASSISTIDO");
            entity.Property(e => e.Titulo)
                .HasMaxLength(255)
                .IsUnicode(false)
                .HasColumnName("TITULO");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}