// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyFlix.DAO.Models;

public partial class Filme
{
    public int Id { get; set; }

    public string Titulo { get; set; }

    public string Genero { get; set; }

    public DateTime AnoLancamento { get; set; }

    public int Nota { get; set; }

    public string Poster { get; set; }


    public bool StatusAssistido { get; set; }

    public DateTime DataCadastro { get; set; }
}